# Generated by Django 4.2.20 on 2025-04-05 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LibroMayor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_anterior', models.FloatField()),
                ('movimiento', models.FloatField()),
                ('saldo_final', models.FloatField()),
                ('cuenta', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalogo.cuenta')),
                ('tipo_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.tipo')),
            ],
        ),
    ]
