# Generated by Django 4.2.20 on 2025-04-05 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libromayor',
            name='cuenta',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.cuenta'),
        ),
    ]
