# Generated by Django 4.2.20 on 2025-04-30 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_alter_libromayor_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libromayor',
            name='saldo_final',
            field=models.FloatField(editable=False),
        ),
    ]
