# Generated by Django 4.2.20 on 2025-04-30 02:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_alter_libromayor_saldo_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='libromayor',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='libromayor',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='libromayor',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='libromayor',
            name='movimiento',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='libromayor',
            name='saldo_anterior',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='libromayor',
            name='saldo_final',
            field=models.FloatField(default=0.0),
        ),
    ]
