# Generated by Django 4.2.20 on 2025-04-05 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('partidas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalles',
            name='catalogo_cuentas',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalogo.cuenta'),
        ),
    ]
