# Generated by Django 4.2.20 on 2025-04-05 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0002_detalles_catalogo_cuentas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalles',
            old_name='monoto_haber',
            new_name='monto_haber',
        ),
    ]
